Update action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -12,11 +12,18 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Fail on Windows
+      if: ${{ runner.os == 'Windows' }}
+      shell: bash
+      run: |
+        echo "::error::This action does not currently support Windows runners."
+        exit 1
+
     - name: Add Virtual Environment to System Path
       shell: bash
       run: |
-        cat ${GITHUB_PATH} > '${{ runner.temp }}/.original-path'
-        echo "$(dirname $(poetry env info --executable) || realpath '.venv/bin'):${PATH}" > ${GITHUB_PATH}
+        cat ${GITHUB_PATH} > ${{ runner.temp }}/.original-path
+        echo "$(dirname $(poetry env info --executable) || realpath .venv/bin):${PATH}" > ${GITHUB_PATH}
 
     - name: Set Working Directory
       shell: bash
@@ -44,7 +51,7 @@ runs:
     - name: Get Cache Key I
       id: key-1
       shell: bash
-      run: python '${{ github.action_path }}/key.py'
+      run: python ${{ github.action_path }}/key.py
       working-directory: ${{ env.REFLEX_EXPORT_CWD }}
 
     - name: Restore Cache
@@ -63,7 +70,7 @@ runs:
     - name: Get Cache Key II
       id: key-2
       shell: bash
-      run: python '${{ github.action_path }}/key.py'
+      run: python ${{ github.action_path }}/key.py
       working-directory: ${{ env.REFLEX_EXPORT_CWD }}
 
     - name: Save Cache
@@ -75,4 +82,4 @@ runs:
     - name: Restore System Path
       if: ${{ always() }}
       shell: bash
-      run: cat '${{ runner.temp }}/.original-path' > ${GITHUB_PATH}
+      run: cat ${{ runner.temp }}/.original-path > ${GITHUB_PATH}
