Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,6 +8,13 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Exit on Windows
+      if: ${{ runner.os == "Windows" }}
+      shell: bash
+      run: |
+        echo "::error::This action does not currently support Windows runners."
+        exit 1
+
     - name: Set Up uv
       uses: astral-sh/setup-uv@v3
 
